### PR TITLE
Br tags closed

### LINKED ISSUE #158: [Bug] Incorrect Closing of `br` tags in some html files
## Description
In the html files below, the br tag is wrongly closed there by preventing prettier from formatting the code.

in docs folder:
1. index.html

In specimen > contents:
1. archive-page
2. blog-index
3. blog-post
4. default-page
5. home-index
6. license-page
7. person-page
8. program-index
9. search-index
10. team-index
11. walkthrough-page

in tests folder:
1. index-logo
2. index.html
3. product-logo

The incorrect way the br tag is written prevents prettier from formatting the code.

1.The br tag should be correctly closed, this will enable prettier work without throwing error(s).

- [ ] I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by SisiVero**
## Fixes
- Fixes #158  by @SisiVero

## Description
This Pull Request addresses the issues of wrongly closed tags in the html files below:
In docs folder:
index.html

In specimen > contents:
archive-page
blog-index
blog-post
default-page
home-index
license-page
person-page
program-index
search-index
team-index
walkthrough-page

In tests folder:
index-logo
product-logo

## Tests
1. The br tags were correctly closed in the affected html files.
2. Prettier formats the code now.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

### CODE REVIEW

**Comment by SisiVero** [comment]
Hi @possumbilities , while I try to figure out what went wrong with the other branch, I've created a new one and applied all the changes. Please check and confirm.

I will also personally look into what caused the checks to fail in the previous branch to prevent future occurrences.

**Comment by possumbilities** [comment]
Hi @SisiVero I think you're still missing the `program-index.html` file, but otherwise the whole of this looks stable :)

**Comment by SisiVero** [comment]
``

> Hi @SisiVero I think you're still missing the `program-index.html` file, but otherwise the whole of this looks stable :)

I will check, effect the change and revert, immediately.

**Comment by SisiVero** [comment]
Hi @possumbilities ,I just checked and according to gitlense, you fixed the syntax error for that file 3 weeks ago.
So, the tag is correctly closed in that file.

**Comment by possumbilities** [comment]
@SisiVero You're right! excellent spot. Moving towards Approval!

**Review by possumbilities — APPROVED** [review]
Excellent work, and good job at sticking with this and not giving up!

Approved.

**Comment by SisiVero** [comment]
> Excellent work, and good job at sticking with this and not giving up!
> 
> Approved.

Thank you so much

**Pull request merged**
