### PR TITLE
replaced span with figcaption

### LINKED ISSUE #69: [Bug] Fix Nested Anchor Tags in Attribution Figure and Improve Semantics
### Description
There’s an issue with the attribution markup in image figures, where nested `<a>` tags are used, causing invalid HTML. This can lead to rendering inconsistencies and affect accessibility. Also, the attribution text is currently placed inside a `<span>`, which is not semantically ideal for this use case
### Reproduction

1. Fix the nested `<a>` tags: Ensure that each link is placed in its own distinct anchor tag.

2. Use `<figcaption>` for better semantics: The attribution text would be better suited inside a `<figcaption>` tag, which is designed to describe the content of the figure element.

### Expectation
The HTML should validate correctly, the markup should be more accessible, and the figure captions should follow proper semantic standards for web content

 ### Screenshots
Screenshot 2024-10-03 at 10 32 30 AM

### Environment
 - Device: ( laptop)
 - OS: (MacOS Ventura 13.2.1)
 - Browser: (Chrome)
 

### Additional context
This fix will resolve HTML validation issues caused by nested anchor tags and improve semantics and accessibility by using `<figcaption>` for better image description structure.

### Resolution
 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by Annahbellah**
## Fixes
- Fixes #69  by @annahbellah

## Description
This pull request resolves the problem about the attribution markup in the image figures by replacing the <span> with <figcaption>. This helps in improving the semantic structure of the HTML.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by possumbilities** [comment]
@Annahbellah This Issue is still set as `status: tick work required` Please do not submit PRs against Issues until they have moved to `status: ready for work`. 

Please see the [Contribution Guidelines](https://opensource.creativecommons.org/contributing-code/)

I will leave this PR open for now, but please follow the Contribution Guidelines in the future

**Comment by Annahbellah** [comment]
@possumbilities well acknowledged, I'm sorry for the mistake.

**Comment by possumbilities** [comment]
Hi @Annahbellah Work here would need to address this in all locations, not just the one file. It would also need to verify that by changing the markup in this way that page rendering is not altered.

**Comment by Annahbellah** [comment]
Thank you @possumbilities. I have worked on this like you instructed.

**Review by possumbilities — APPROVED** [review]
Thank you for this! Approved.

**Pull request merged**
