### PR TITLE
Add GitHub Actions Workflow for Linting 

### LINKED ISSUE #5: Research CSS organization standards, tools, and best practices; and provide routes of implementation for documentation and linting
## Problem

We need some documented guidelines for how our CSS is crafted so that we can:
* have predictable and documented best practices for all contributors to follow
* possibly lint most or all of those best practices to aide with more organized code.

## Description
Continued from a comment here: 
* https://github.com/creativecommons/creativecommons.org-prototype/pull/19#discussion_r1184042143

@possumbilities 
> Ordering the lines is a much more complex sub-project I haven't tackled just yet because the order of the property:value pair declarations in a style rule is the order (generally) they are applied/executed, which means there are situations where certain properties need to be set before others for varied reasons: cross-browser quirks, flash of un-styled content bugs, performance, and even feature fallbacks. This makes CSS particularly powerful, but also (at times) annoyingly resistant to easy alphabetizing of properties on the whole or other simple line order procedures. There's also "folk" conventions of what things should be together and what order they should be in for "readability and modification based on what they do", like putting height and width together in the order because they are so heavily tied together, often changed together, calculated together at render, and so on. With that much variation I haven't devoted time to a sensible documented "guideline" for our CSS here just yet.
> 
> I want there to be reasonable guidelines for CSS file org, but haven't applied much yet because I want to get most everything in there, and also find some pre-existing standards/guides/etc. we could point to, or fallback on. Ordering property:value pairs in CSS is like alphabetizing lines in a programming function, a better read order may break expected outcomes of function, and I want a sound through-line to lean on for what we do, before I start trying to do something so I can more easily document it, and even lint it if possible. Which is why for the time being I've just split them into two groups only, but do plan to do more org in this area :)

The above quote is mostly to do with us needing some level of guidelines for how we organize and/or order our CSS. 

At best CSS style rules have grown over time to make their terminology in conflict with how they tend to be considered. 

In CSS we have 
* Rules
* Properties
* Values

In general, where possible in code we would want `property:value` pairs to be ordered in an organized fashion, likely alphabetical. However, CSS rules, particularly in current featureset, are actually closer to scoped-ish functions in most programming languages, and property:value pairs are similar to executable lines in a function.

Which makes this in CSS:

`````

article {
--var-color: blue;

width: 40px;
height: 100vh;

font-family: Arial;
text-decoration: none;

}

`````

similar to the following pseudo programming code:

`````

function article {
var color = blue;

this.dimension.width = calc.byUnit(40, "px");
this.dimension.height = calc(window.rendered.height);

this.font.family = "Arial";
this.text.decoration = "none";

}

`````

Since there are situations where the line order can matter in a CSS rule, the same as in a standard programming function situation, merely alphabetizing the lines within the rule doesn't necessarily result in stable expected outcomes.

Therefore, we could do with documenting various approaches we could build from, borrow from, or adopt.

## Implementation

- [x] I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by Vanessa082**
## Related to
- Fixes #5  by @Vanessa082 

## Description
This PR adds a GitHub Actions workflow to implement linting for HTML, CSS, and JavaScript files in the project. The workflow runs on pushes and pull requests to the `main` branch and utilizes the `github/super-linter` action for code linting.

## Technical details
- A new GitHub Actions workflow file is created with the following specifications:
  - Triggered on push and pull request events.
  - Checks out the code base to ensure the latest changes are included.
  - Runs the Super Linter against the code base, validating the code style according to established best practices.

## Tests
To verify that this PR functions correctly:
1. Push changes to a branch and create a pull request to the `main` branch.
2. Check the Actions tab in the GitHub repository to see if the linting job runs successfully.
3. Review the results of the linting to ensure there are no errors.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open-source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by Vanessa082** [comment]
@TimidRobot  @possumbilities I want to provide you with an update on the progress I've made regarding issue #5, which required research into CSS organization standards, tools, and best practices.
I have implemented  Super Linter in my forked Vocabulary repository and created a pull request from my main branch. The linter has provided a comprehensive report, and I’ve noticed that there are quite a few linter errors that need to be addressed.
Before I proceed with fixing these errors, I wanted to confirm if I'm allowed to go ahead and make these changes. Additionally, if you have any specific guidelines or best practices that you would recommend for addressing the linter errors, I would greatly appreciate your insights.
image

**Comment by possumbilities** [comment]
@Vanessa082 Thank you for this contribution! However, this does not satisfy the Issue it is connected to. Standards would need to be decided within that Issue before implementing them. This is skipping a step. 

Closing, as its not resolving the Issue.

**Comment by Vanessa082** [comment]
Thank you, @possumbilities 
I am a little confused and unsure about my next steps.
I have researched and studied BEM (Block Element Modifier), ITCSS (Inverted Triangle CSS), CSS Property Ordering, CSS Variables and Global Settings, CSS Specificity and Avoidance of Conflicts, and I’ve even reviewed CSS selectors on MDN.
Now, here’s my concern:
I don’t know whether I should start correcting the code immediately that is going through the code to see. For example, I’ve noticed that line spacing isn’t being respected, though this may not be the best example. I mentioned this because it's one of the reasons I considered using a linter.
I am also confused about whether I should start with documentation before making any changes and with the documentation should I write what I learned and researched or should I look into the css written and remove best practices and document on because it looks like there is more to this that meets the eye
Could you kindly guide me on the best course of action?

**Comment by possumbilities** [comment]
@Vanessa082 Hi! 

On the original Issue there should be final determinations around which standards and formatting would be utilized before trying to implement standards and formatting provided as defaults by external tooling. If you have suggestions for such standards or formatting that we should follow include it with evidence as a comment on that original Issue.

**Pull request closed without merging**
