### PR TITLE
Update CSS to follow style rules

### LINKED ISSUE #177: [Bug] Vocabulary css style rules not being followed.
## Description
In the vocabulary.css file, the style rule or guides for writing style rules which are:
Style rules are written with two sections
at current, separated by an empty line.

1. for layout, positioning, and related.

2. for visual configuration such
as color, font, background, etc.

are not being followed in some of the css styles.

## Reproduction

1. Calmly read through the written css styles.
2. Ensure that they adhere to the guide; layout in the first section, and empty line, then visuals in the second section.

## Expectation
1. Layout styling should be written in the first section.
2. An empty line should demarcate the first section from the second section. 

- [ ] I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by Queen-codes**
## Fixes

- Fixes #177 by @SisiVero

## Description
This PR formats the `vocabulary.css` file to adhere to the specified rules concerning the layout and visual properties being separated by a line. With this PR, the layout properties are in the first section, demarcated by a line and then followed by the visual properties.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by possumbilities** [comment]
@Queen-codes ~when you've moved items, be sure to also remove the empty line that item was occupying too.~

**Comment by possumbilities** [comment]
@Queen-codes Please resolve the conflicts with this PR when you have a moment. I think otherwise its close to Approval. Thanks!

**Comment by Queen-codes** [comment]
> @Queen-codes Please resolve the conflicts with this PR when you have a moment. I think otherwise its close to Approval. Thanks!

hi @possumbilities . resolved, thanks.

**Review by possumbilities — APPROVED** [review]

**Comment by possumbilities** [comment]
@Queen-codes If you comment on the original issue I can assign you.

**Pull request merged**
