### PR TITLE
fix-remove invalid attribute from <article> element-234

### LINKED ISSUE #234: [Bug] Attribute e Not Allowed on Element article
## Description
- Message: Attribute e not allowed on element article at this point.
- Location: From line 123, column 13 to line 123, column 38 in theprogram-index.html file under the context folder.
- Code Extract: article class="project"e

## Reproduction
- Open the HTML file containing the error.
- Navigate to line 123.
- Observe the article element with an incorrect attribute.
- Verify the error in the console or during validation.

## Expectation
The article element should not have any attributes that are not allowed, such as e. The expected behavior is for the attribute to be removed or corrected.

## Screenshots
Screenshot (310)

## Resolution
- [x] I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by Asheklm6**
## Fixes

- Fixes #234  by @possumbilities 

## Description

This PR fixes an invalid attribute in the <article> element of the program-index.html file. The extraneous "e" after the class attribute was removed.

## Tests

Open the modified program-index.html file.
Verify that the extraneous "e" attribute has been removed from the <article> element.
Use an HTML linter to validate that the file is now error-free.
## Checklist

- [x ] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x ] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x ] My commit messages follow [best practices][best_practices].
- [x ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x ] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by possumbilities — APPROVED** [review]
Thanks for this! Approved.

**Comment by possumbilities** [comment]
@Asheklm6 if you comment on the original Issue I can Assign you!

**Comment by Asheklm6** [comment]
@possumbilities Alright, i will right away. Thank you.

**Comment by Asheklm6** [comment]
@possumbilities I just left a comment  on the original issue, so you can assign me.

**Pull request merged**
