### PR TITLE
Changed the spelling mistake of Ancillary

### LINKED ISSUE #184: [Bug] There is a Spelling Mistake of Ancillary in the Code
## Description
There is a misspelling of "Ancillary" in the website UI, as well as in the HTML file located in the docs folder. This spelling error should be corrected for professionalism. After correcting it in the docs/index.html file, we must also update all instances where the class with the incorrect spelling is used, specifically in src/css/vocabulary.css. This will improve the overall quality of our website.

## Reproduction
1. Navigate to the docs folder in the Vocabulary project.
2. Open the index.html file and check lines 207 and 248.
3. You will see the misspelling of "Ancillary" there.
4. Verify the error in the UI.

## Screenshots

Screenshot 2024-10-13 021523
Screenshot 2024-10-13 021531
Screenshot 2024-10-13 021852
Screenshot 2024-10-13 021936

## Environment

 - Device: (_eg._ iPhone Xs; laptop)
 - OS: (_eg._ iOS 13.5; Fedora 32)
 - Browser: (_eg._ Safari; Firefox)
 - Version: (_eg._ 13; 73)
 - Other info: (_eg._ display resolution, ease-of-access settings)

## Resolution

- [x] I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by Raja-Abrar-Khan**
## Fixes
- Fixes #184 by [Raja-Abrar-Khan](https://github.com/Raja-Abrar-Khan)

## Description
I corrected the spelling of "Ancillary" in all files where the term was misspelled, including the docs/index.html file and all other relevant files in the project folder. This update ensures consistent usage across the project and improves the professionalism of the website's UI.

## Technical details

.Updated the spelling of "Ancillary" in:
  -docs/index.html (lines 207 and 248)
  -src/css/vocabulary.css
  -All other files across the project where the incorrect spelling appeared, including HTML, CSS, and any other source files using 
   the term.
## Tests

To verify this PR:

1. Go through the website and check any sections where the term "Ancillary" is displayed to confirm the correction.
2. Review the project to ensure that all references to the CSS class with the incorrect spelling have been updated.

## Screenshots

Screenshot 2024-10-13 225411

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by SisiVero** [comment]
Hi, @Raj, great work.
However, the issue is not yet marked "ready for work", hence you cannot make a PR until it has been marked "ready for work".
You ca read the guides to now what issue to work on and hat issue to not work on: https://github.com/SisiVero/CC-guides/blob/main/README.md

**Comment by possumbilities** [comment]
@Raja-Abrar-Khan Hi, and thanks for your enthusiasm 

Yes, please don't open PRs before things have moved to `status: ready for work`

Please see the [Contribution Guidelines](https://opensource.creativecommons.org/contributing-code/) for more info.


Additionally, we try not to do formatting changes grouped with other changes, please revert the additional changes you've made to this PR, so that the changes reflect only what is outlined in the Issue it is addressing.

**Comment by possumbilities** [comment]
@Raja-Abrar-Khan Please remove the extra formatting changes, so this PR only addresses the spelling fixes associated with this Issue.

**Comment by Raja-Abrar-Khan** [comment]
Thank you for your feedback! I will ensure that the PR only includes the necessary spelling fixes for "Ancillary." I’ll review the changes and remove any unrelated formatting adjustments.

**Comment by possumbilities** [comment]
replaced by:
- #214 

Closing.

**Pull request closed without merging**
