### PR TITLE
BugFix: Closed open <link> tags in files mentioned in issue #170

### LINKED ISSUE #170: [Bug] <link> tags not closed in all contexts pages
## Description
1. Currently in all the html files in context folder, the <link> tags in lines 8, 9, 10 and 13 are not closed.
2. In index-logo and product-logo files of tests folder, the <link> tags in line 8 of each files are not closed.
3. In index.html of docs folder, the <link.> tags in lines 8 and 125 are not closed.

## Reproduction

1. Go the listed folders
2. Open each file listed.
6.Check the lines mentioned
7. See error.

## Expectation
The <link> tags should be closed as it is a self terminating tag. 

## Screenshots
Below are screenshots from the codes:
contexts files:
contextsPages

index-logo:
index-logo

index.html (docs folder)
docsindex html

- [ ] I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by SumaiyaaRq**
## Fixes

- Fixes #170 by @SisiVero

## Description
This PR resolves the issue #170 by closing all open link tags in the mentioned files .

## Technical details
The simple bug issue has been fixed by closing all the <link> tags that were not previously in the files listed in the issue.

## Tests
1.Go to the listed folders.
2.Open mentioned files
    a)Check the lines for closed tags

## Screenshots
Files in contexts folder-Before:

Screenshot 2024-10-11 at 10 07 11 PM

Files in contexts folder-After:

Screenshot 2024-10-11 at 10 03 42 PM
 
Other files after correction:
index-logo.html  &  product-logo.html:
Screenshot 2024-10-11 at 10 05 26 PM
docs folder->index.html:
Screenshot 2024-10-11 at 10 04 53 PM
Screenshot 2024-10-11 at 10 05 14 PM

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by possumbilities** [comment]
@SumaiyaaRq This is very helpful, but we'd want to have a space preceding the end. So instead of `"/>` we would want `" />`

**Comment by SumaiyaaRq** [comment]
@possumbilities  Thank you for your feedback! 
I will try to make the required changes asap.

**Comment by SumaiyaaRq** [comment]
@possumbilities I have changed the code as per the requirements. I  am not sure if I can change the previously uploaded screenshots as I am still learning about GitHub! I am adding one screenshot herewith to show the changes :
Screenshot 2024-10-11 at 11 24 03 PM

**Review by possumbilities — APPROVED** [review]
Looks good! Thank you. Approved.

**Comment by possumbilities** [comment]
@SumaiyaaRq If you comment on #170 I can assign you for credit

**Comment by SumaiyaaRq** [comment]
@possumbilities Thank you so much! This is my first ever PR in Open Source that has got approval!! 
I am overjoyed!😁

**Comment by possumbilities** [comment]
@SumaiyaaRq that's wonderful! congratulations! ❤️

**Comment by possumbilities** [comment]
@SumaiyaaRq Also, I think there are other files within the `specimen` directory that were missed in this Issue and related PR only focused on the contexts, please verify and if missed make a new Issue for those missed files.

**Comment by SumaiyaaRq** [comment]
@possumbilities Thank you for the wish! 
I would definitely look for files with similar issue and raise a request accordingly.

**Pull request merged**
