### PR TITLE
Fix URL syntax in @font-face declarations for improved browser compatability

### LINKED ISSUE #100: [Bug] Incorrect URL Syntax in @font-face Declarations
## Description
Incorrect URL syntax in `@font-face` declaration. The `url()` value is not enclosed in quotes, which may lead to unexpected behavior in certain browsers.

## Reproduction
1. Open the CSS  library-vars.css file containing the `@font-face` declarations.
2. Locate the `@font-face` rules for fonts such as "Source Sans Pro" and "Roboto Condensed."
3. Observe that some `url()` values are not enclosed in quotes.
4. See error.

## Expectation

The `URL ()` value should be enclosed in quotes to ensure consistent behavior across all browsers.

## Screenshots
Screenshot from 2024-10-05 13-32-35
## Environment
 - Device:  Laptop
 - OS: Linux
 - Browser: Chrome

## Resolution
- [x] I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by Vanessa082**
Fixes
- #100  

## Description
This pull request addresses an issue with incorrect URL syntax in the `@font-face` declarations within the CSS file. The URLs for the font files were not enclosed in quotes, which could lead to inconsistent font loading behavior across different browsers.

## Technical details
The implementation fixes the syntax by enclosing all `url()` values in single quotes. This change ensures that the CSS adheres to best practices and enhances compatibility with various browsers. The affected `@font-face` declarations include those for "Roboto Condensed," "Source Sans Pro," and "CC Accidenz Commons."

## Tests
1. Open the CSS file and review the `@font-face` declarations.
2. Verify that all `url()` values are now properly enclosed in quotes.
3. Test the website in multiple browsers to ensure that fonts are loading consistently without errors.

## Checklist
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]: https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```
</details>

### CODE REVIEW

**Comment by possumbilities** [comment]
@Vanessa082 please revert all formatting changes unrelated to this Issue. The only changes present within this PR should be the addition of quotes around the urls' values.

**Comment by Vanessa082** [comment]
@possumbilities I just did that now

**Comment by possumbilities** [comment]
@Vanessa082 It looks like you haven't merged in more recent changes from the `main` branch and that is causing the preview build to fail. Please update your branch with those changes and push here and that should resolve it.

**Comment by Vanessa082** [comment]
Thank you @possumbilities I just updated

**Review by possumbilities — APPROVED** [review]

**Comment by possumbilities** [comment]
@Vanessa082 Wonderful! Thank you. Approved.

**Pull request merged**
