### PR TITLE
Fix FOUC Issue: Implement Font Preloading and

### LINKED ISSUE #11: [Bug] FOUC (flash of unstyled content) occurs erratically, causes a layout shift prior to fonts loading/rendering correctly
## Description
When the site is first loaded, there is a brief FOUC, which delays the proper rendering of the included font-files, icons, etc.. This results in a layout shift on first load. 

Afterwards, the files are cached and this doesn't usually occur again, but it is something we should address.

## Reproduction

1. Disable browser caching/reset cache
2. Visit creativecommons.org
3. See error.

## Expectation
Site should load more smoothly on initial payload.

## Screenshots
Screen Shot 2023-10-18 at 2 05 35 PM

## Resolution

- [x] I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by RonaldRonnie**
- fixes #11 

Visibility Management

- Added `<link rel="preload">` for Google Fonts
to optimize loading.
- Introduced JavaScript to manage body visibility
 based on font loading status.
- Applied CSS transitions for a smoother user
experience.
- Ensured content is hidden until fonts are fully
 loaded to prevent layout shifts.

### CODE REVIEW

**Comment by Queen-codes** [comment]
Hi @RonaldRonnie. Keep up the good work! 

I just wanted to bring a couple things to your attention. When creating this PR, there was a format there. You should follow that format. This allows mentors to know what issue you're solving. It also contains essential information that helps make the code review process easier for them. I noticed the remaining two PRs you created have this issue. You can check out the [PR Guidelines](https://opensource.creativecommons.org/contributing-code/pr-guidelines/).  

If you need a visual reference for how PRs are supposed to look, I can provide one or you can check examples of how other people have been making their PRs. Let me know what you think. Have fun contributing!

**Comment by SisiVero** [comment]
Yes @RonaldRonnie , Queen is right.
Also, if there ais no open issue for the feature you implemented, you can open an issue for it and when it gets set "ready for work", you can work on it.
You can read through already opened issues and PR to see how it works or looks.

**Comment by possumbilities** [comment]
@RonaldRonnie Hi! please attach this to an existing issue, or I'll move it to Closed soon.

**Comment by RonaldRonnie** [comment]
let me do this right away please

**Comment by possumbilities** [comment]
Hi @RonaldRonnie This PR doesn't doe what is claims to, and doesn't utilize the original PR Template. 

I am closing this for now, feel free to open further PRs, and please follow the [Contribution Guidelines](https://opensource.creativecommons.org/contributing-code/)

**Pull request closed without merging**
