### PR TITLE
Default page div closed

### LINKED ISSUE #111: [Bug] No closing div tag in default page html
## Description
There is an open div tag that does not have a closing tag in the default-page.html, code line 138.
- [x] I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by SisiVero**
## Fixes

- Fixes #111  by @SisiVero

## Description
A closing div tag was added to default page html for the open div tag in line 138 with class "content"

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

### CODE REVIEW

**Comment by possumbilities** [comment]
Hi! and thank you for your excitement. Please do not submit PRs against Issues that have not yet moved to `status: ready for work`.

Please see the [Contribution Guidelines](https://opensource.creativecommons.org/contributing-code/) for more information.

I'll leave this PR open for now, but please follow the Contribution Guidelines in the future.

**Comment by SisiVero** [comment]
Hi @possumbilities , I'm so sorry. I'll follow the guidelines henceforth. 
Thank you.

**Comment by possumbilities** [comment]
This was fixed by #134 (I missed this PR going back through so I'm going to assign both of you to the Issue)

Closing.

**Comment by iyinolawumi** [comment]
Ok. Thank you @possumbilities 
Well done @SisiVero

**Pull request closed without merging**
